ALL: ex1 ex2 ex3
CFLAGS= -w

.PHONY:clean

clean:
	@echo Porque Kenny!
	 \rm -f *.o ex1 ex2 ex3

ex1: exercise1.c
	cc $(CFLAGS) exercise1.c -g -o ex1

ex2: exercise2.c
	cc $(CFLAGS) exercise2.c -g -o ex2

ex3: exercise3.c
	cc $(CFLAGS) exercise3.c -g -o ex3
