ALL: Factorial Integral Time_Child pstree Multiprogram
CFLAGS=-std=c11 -w

.PHONY:clean

clean:
	@echo Porque Kenny!
	 \rm -f Factorial Integral Time_Child pstree Multiprogram

Factorial: exercise1.c
	gcc $(CFLAGS) exercise1.c -g -o Factorial

Integral: exercise2.c
	gcc $(CFLAGS) exercise2.c -g -o Integral

Time_Child: excercise3.c
	gcc $(CFLAGS) excercise3.c -g -o Time_Child

pstree: exercise4.c
	gcc $(CFLAGS) exercise4.c -g -o pstree

Multiprogram: exercise5.c
	gcc $(CFLAGS) exercise5.c -g -o Multiprogram

